package com.probeflow.testagent.memorygraph;

public enum MemoryGraphRelationType {
    MEMORY_MENTIONS_ENTITY,
    ENTITY_RELATED_TO_MEMORY,
    API_BELONGS_TO_MODULE,
    MODULE_BELONGS_TO_SYSTEM,
    API_USES_HTTP_METHOD,
    ERROR_OBSERVED_ON_API,
    FAILURE_CLASSIFIED_AS,
    BUSINESS_ENTITY_RELATED_TO_API,
    BUSINESS_ENTITY_REQUIRES_PRECONDITION,
    SUITE_CONTAINS_CASE,
    SUITE_STEP_PRODUCES_VARIABLE,
    SUITE_STEP_CONSUMES_VARIABLE,
    VARIABLE_EXTRACTED_FROM_SOURCE_PATH,
    POLICY_REASON_APPLIES_TO_TOOL,
    FACT_HAS_TYPE,
    FACT_HAS_TAG,
    FACT_REINFORCES_FACT,
    FACT_CONFLICTS_WITH_FACT
}
