package com.probeflow.testagent.agentpolicy;

public enum ToolPrecondition {
    TASK_EXISTS,
    SOURCE_MATERIAL_AVAILABLE,
    API_SPEC_AVAILABLE,
    CONTEXT_BUNDLE_AVAILABLE,
    TEST_CASE_DRAFT_EXISTS,
    TEST_CASE_DRAFT_REVIEWED,
    TEST_CASE_EXISTS,
    EXECUTION_RECORD_EXISTS,
    FAILURE_SIGNAL_AVAILABLE,
    OBSERVATION_EXISTS,
    REPORT_DATA_AVAILABLE,
    EXECUTION_READINESS_CONFIRMED
}
