package com.probeflow.testagent.policyvalidator;

public enum PolicyValidationReasonCode {
    SAFE_CONTINUE,
    SAFE_INSERT_STEP,
    SAFE_REPLAN,
    SAFE_STOP,
    HUMAN_INPUT_REQUIRED,
    MISSING_HUMAN_INPUT,
    MISSING_PROPOSED_STEP,
    STOP_WITH_TOOL_INTENT,
    PLANNER_BLOCKED,
    PLANNER_FAILED,
    TOOL_ALLOWED_BY_POLICY,
    UNKNOWN_TOOL,
    TOOL_NOT_VISIBLE,
    TOOL_NOT_WHITELISTED,
    TOOL_BLOCKED_BY_CONTRACT,
    TOOL_NOT_ALLOWED_IN_TASK_PHASE,
    MISSING_REQUIRED_INPUT,
    INVALID_INPUT_TYPE,
    INVALID_INPUT_VALUE,
    MISSING_PRECONDITION,
    HUMAN_CONFIRMATION_REQUIRED,
    REVIEW_REQUIRED_WORKFLOW,
    V1_BOUNDARY_BLOCKED,
    INVALID_REQUEST
}
