package com.probeflow.testagent.failureanalysis;

public enum FailureClassification {
    NONE,
    ASSERTION_FAILURE,
    STATUS_MISMATCH,
    RESPONSE_SHAPE_MISMATCH,
    RESPONSE_VALUE_MISMATCH,
    BODY_PRESENCE_FAILURE,
    DURATION_REGRESSION,
    TRANSPORT_ERROR,
    TIMEOUT,
    BLOCKED_REQUEST,
    ENVIRONMENT_ISSUE,
    AUTH_ISSUE,
    VALIDATION_ISSUE,
    SERVER_ERROR,
    SUITE_PREREQUISITE_FAILURE,
    SKIPPED,
    PASSED_WITH_WARNING,
    DATA_QUALITY_ISSUE,
    UNKNOWN
}
